@startuml
interface ICliSession {
    ModeName : string <<get>>
    ExecuteCommand(command:string, args:string[], options:Dictionary<string, string>) : void
    PrintHelp() : void
}
class CliEngine {
    + CliEngine(session:ICliSession)
    + Run() : void
    - ParseAndExecute(input:string) : void
    - ParseArguments(input:string) : List<string>
}
CliEngine --> "_session" ICliSession
@enduml
