@startuml
class CommandRegistry {
    + Register(command:ICommand) : void
    + GetCommand(keyword:string) : ICommand?
    + GetAll() : IEnumerable<ICommand>
    + RegisterFromAssembly(assembly:Assembly) : void
}
class "Dictionary`2"<T1,T2> {
}
CommandRegistry o-> "_commands<string,ICommand>" "Dictionary`2"
@enduml
