@startuml
class TextSession {
    + ModeName : string <<get>>
    + TextSession(registry:CommandRegistry)
    + PrintHelp() : void
    + ExecuteCommand(command:string, args:string[], options:Dictionary<string, string>) : void
}
ICliSession <|-- TextSession
TextSession --> "_registry" CommandRegistry
@enduml
