@startuml
class CharacterStats {
    + CharacterStats()
    + CharacterStats(other:CharacterStats)
    + GetStat(type:StatType) : int
    + SetStat(type:StatType, value:int) : void
    + ModifyStat(type:StatType, delta:int) : void
}
class "Dictionary`2"<T1,T2> {
}
CharacterStats o-> "_stats<StatType,int>" "Dictionary`2"
@enduml
