@startuml
class AttackResult <<record>> {
    + Attacker : string <<get>> <<init>>
    + Target : string <<get>> <<init>>
    + Damage : int <<get>> <<init>>
}
class AbilityResult <<record>> {
    + User : string <<get>> <<init>>
    + Target : string <<get>> <<init>>
    + AbilityName : string <<get>> <<init>>
    + Damage : int <<get>> <<init>>
}
class HealResult <<record>> {
    + Healer : string <<get>> <<init>>
    + Amount : int <<get>> <<init>>
}
@enduml
