@startuml
class Container {
    + Container(name:string, parent:Container?)
    + AddChild(child:IText) : void
    + RemoveChild(nameOrId:string) : bool
    + FindChild(nameOrId:string) : IText?
    + GetChildren() : IEnumerable<IText>
    + <<override>> Render() : string
}
class "List`1"<T> {
}
TextBase <|-- Container
Container o-> "_children<IText>" "List`1"
@enduml
