@startuml
abstract class TextBase {
    + Name : string <<get>> <<protected set>>
    # TextBase(name:string)
    + {abstract} Render() : string
}
IText <|-- TextBase
TextBase o-> "Id" Guid
TextBase --> "Parent" Container
@enduml
