@startuml
class ActCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + ActCommand(system:ICombatSystem, context:WorldContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
ICommand <|-- ActCommand
ActCommand --> "_system" ICombatSystem
ActCommand --> "_context" WorldContext
@enduml
