@startuml
class Program {
    {static} - Main(args:string[]) : void
}
class Paragraph {
    - _content : string
    + Paragraph(content:string)
    + Paragraph(name:string, content:string)
    + <<override>> Render() : string
}
TextBase <|-- Paragraph
interface IText {
    Name : string <<get>>
    Render() : string
}
IText --> "Id" Guid
IText --> "Parent" Container
class DocumentContext {
    + DocumentContext()
}
DocumentContext --> "Root" Root
DocumentContext --> "CurrentContainer" Container
abstract class TextBase {
    + Name : string <<get>> <<protected set>>
    # TextBase(name:string)
    + {abstract} Render() : string
}
IText <|-- TextBase
TextBase o-> "Id" Guid
TextBase --> "Parent" Container
class Root {
    + Root(name:string)
    + <<override>> Render() : string
}
Container <|-- Root
enum TextType {
    Heading,
    Paragraph,
}
class TextFactory {
    + AddElement(context:DocumentContext, type:TextType, nameOrContent:string) : void
}
class Container {
    + Container(name:string, parent:Container?)
    + AddChild(child:IText) : void
    + RemoveChild(nameOrId:string) : bool
    + FindChild(nameOrId:string) : IText?
    + GetChildren() : IEnumerable<IText>
    + <<override>> Render() : string
}
class "List`1"<T> {
}
TextBase <|-- Container
Container o-> "_children<IText>" "List`1"
class Heading {
    - <<readonly>> _rank : int
    + Heading(name:string, rank:int, parent:Container?)
    + <<override>> Render() : string
}
Container <|-- Heading
interface ICombatLogger {
    LogAttack(result:AttackResult) : void
    LogAbility(result:AbilityResult) : void
    LogHeal(result:HealResult) : void
    LogMessage(message:string) : void
}
interface IStatProvider {
    GetModifiers() : Dictionary<StatType, int>
}
interface ICommand {
    Keyword : string <<get>>
    Description : string <<get>>
    Execute(args:string[], options:Dictionary<string, string>) : void
}
interface ICombatSystem {
    Attack(attacker:ICombatEntity, defender:ICombatEntity) : AttackResult
    UseAbility(user:ICombatEntity, target:ICombatEntity, ability:Ability) : AbilityResult
    Heal(healer:ICombatEntity, amount:int) : HealResult
}
interface ICombatEntity {
    Name : string <<get>>
    IsAlive : bool <<get>>
    TakeDamage(amount:int) : void
    Heal(amount:int) : void
    GetStats() : CharacterStats
    GetAbilities() : IEnumerable<Ability>
}
class WorldContext {
}
class "List`1"<T> {
}
WorldContext o-> "Characters<Character>" "List`1"
WorldContext o-> "ItemPool<Item>" "List`1"
abstract class Ability {
    + Name : string <<get>>
    # Ability(name:string)
    + {abstract} CalculateDamage(userStats:CharacterStats, targetStats:CharacterStats) : int
}
abstract class Item {
    + Name : string <<get>>
    # Item(name:string)
    # AddModifier(type:StatType, amount:int) : void
}
class "Dictionary`2"<T1,T2> {
}
Item --> "GrantedAbility" Ability
Item o-> "Modifiers<StatType,int>" "Dictionary`2"
abstract class Character {
    + Name : string <<get>>
    # Character(name:string)
    # SetBaseStat(type:StatType, value:int) : void
    + IsAlive : bool <<get>>
    - GetCurrentHealth() : int
    + TakeDamage(amount:int) : void
    + Heal(amount:int) : void
    + EquipItem(item:Item) : void
    + LearnAbility(ability:Ability) : void
    + GetStats() : CharacterStats
    + GetAbilities() : IEnumerable<Ability>
}
class "List`1"<T> {
}
ICombatEntity <|-- Character
Character --> "_baseStats" CharacterStats
Character o-> "_equipment<Item>" "List`1"
Character o-> "_abilities<Ability>" "List`1"
class CharacterStats {
    + CharacterStats()
    + CharacterStats(other:CharacterStats)
    + GetStat(type:StatType) : int
    + SetStat(type:StatType, value:int) : void
    + ModifyStat(type:StatType, delta:int) : void
}
class "Dictionary`2"<T1,T2> {
}
CharacterStats o-> "_stats<StatType,int>" "Dictionary`2"
class AttackResult <<record>> {
    + Attacker : string <<get>> <<init>>
    + Target : string <<get>> <<init>>
    + Damage : int <<get>> <<init>>
}
class AbilityResult <<record>> {
    + User : string <<get>> <<init>>
    + Target : string <<get>> <<init>>
    + AbilityName : string <<get>> <<init>>
    + Damage : int <<get>> <<init>>
}
class HealResult <<record>> {
    + Healer : string <<get>> <<init>>
    + Amount : int <<get>> <<init>>
}
enum StatType {
    Health,
    MaxHealth,
    Attack,
    Armor,
    Mana,
    Speed,
}
class PowerStrike {
    + PowerStrike()
    + <<override>> CalculateDamage(userStats:CharacterStats, targetStats:CharacterStats) : int
}
Ability <|-- PowerStrike
class Fireball {
    + Fireball()
    + <<override>> CalculateDamage(userStats:CharacterStats, targetStats:CharacterStats) : int
}
Ability <|-- Fireball
class Lightning {
    + Lightning()
    + <<override>> CalculateDamage(userStats:CharacterStats, targetStats:CharacterStats) : int
}
Ability <|-- Lightning
class Shield {
    + Shield()
}
Item <|-- Shield
class Sword {
    + Sword()
}
Item <|-- Sword
class MagicAmulet {
    + MagicAmulet()
}
Item <|-- MagicAmulet
class LightningWand {
    + LightningWand()
}
Item <|-- LightningWand
class Mage {
    + Mage(name:string)
}
Character <|-- Mage
class Warrior {
    + Warrior(name:string)
}
Character <|-- Warrior
class CombatSystem {
    + CombatSystem(logger:ICombatLogger)
    + Attack(attacker:ICombatEntity, defender:ICombatEntity) : AttackResult
    + UseAbility(user:ICombatEntity, target:ICombatEntity, ability:Ability) : AbilityResult
    + Heal(healer:ICombatEntity, amount:int) : HealResult
}
ICombatSystem <|-- CombatSystem
CombatSystem --> "_logger" ICombatLogger
class BattleManager {
    + BattleManager(combatSystem:ICombatSystem, logger:ICombatLogger)
    + AddParticipant(entity:ICombatEntity) : void
    + StartBattle() : void
    - TakeTurn(attacker:ICombatEntity, target:ICombatEntity) : void
}
class "List`1"<T> {
}
BattleManager --> "_combatSystem" ICombatSystem
BattleManager --> "_logger" ICombatLogger
BattleManager o-> "_participants<ICombatEntity>" "List`1"
class GameBuilder {
    + Build() : (CommandRegistry textReg, CommandRegistry charReg, WorldContext, DocumentContext)
}
class CommandRegistry {
    + Register(command:ICommand) : void
    + GetCommand(keyword:string) : ICommand?
    + GetAll() : IEnumerable<ICommand>
    + RegisterFromAssembly(assembly:Assembly) : void
}
class "Dictionary`2"<T1,T2> {
}
CommandRegistry o-> "_commands<string,ICommand>" "Dictionary`2"
interface ICliSession {
    ModeName : string <<get>>
    ExecuteCommand(command:string, args:string[], options:Dictionary<string, string>) : void
    PrintHelp() : void
}
class CliEngine {
    + CliEngine(session:ICliSession)
    + Run() : void
    - ParseAndExecute(input:string) : void
    - ParseArguments(input:string) : List<string>
}
CliEngine --> "_session" ICliSession
class CharacterSession {
    + ModeName : string <<get>>
    + CharacterSession(registry:CommandRegistry)
    + PrintHelp() : void
    + ExecuteCommand(command:string, args:string[], options:Dictionary<string, string>) : void
}
ICliSession <|-- CharacterSession
CharacterSession --> "_registry" CommandRegistry
class TextSession {
    + ModeName : string <<get>>
    + TextSession(registry:CommandRegistry)
    + PrintHelp() : void
    + ExecuteCommand(command:string, args:string[], options:Dictionary<string, string>) : void
}
ICliSession <|-- TextSession
TextSession --> "_registry" CommandRegistry
class CompositeLogger {
    + Add(logger:ICombatLogger) : void
    + LogAttack(result:AttackResult) : void
    + LogAbility(result:AbilityResult) : void
    + LogHeal(result:HealResult) : void
    + LogMessage(message:string) : void
}
class "List`1"<T> {
}
ICombatLogger <|-- CompositeLogger
CompositeLogger o-> "_loggers<ICombatLogger>" "List`1"
class ConsoleLogger {
    + LogAttack(result:AttackResult) : void
    + LogAbility(result:AbilityResult) : void
    + LogHeal(result:HealResult) : void
    + LogMessage(message:string) : void
}
ICombatLogger <|-- ConsoleLogger
ConsoleLogger o-> "_formatter" CombatFormatter
class CombatFormatter {
    + Format(r:AttackResult) : string
    + Format(r:AbilityResult) : string
    + Format(r:HealResult) : string
}
class CreateCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + CreateCommand(context:WorldContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class EquipCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + EquipCommand(context:WorldContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class LsCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + LsCommand(context:WorldContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class "Dictionary`2"<T1,T2> {
}
ICommand <|-- CreateCommand
CreateCommand --> "_context" WorldContext
CreateCommand --> "_characterFactories<string,Func<string, Character>>" "Dictionary`2"
CreateCommand --> "_itemFactories<string,Func<Item>>" "Dictionary`2"
ICommand <|-- EquipCommand
EquipCommand --> "_context" WorldContext
ICommand <|-- LsCommand
LsCommand --> "_context" WorldContext
class AddTextCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + AddTextCommand(context:DocumentContext, factory:TextFactory)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class PrintCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + PrintCommand(context:DocumentContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class PwdCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + PwdCommand(context:DocumentContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class UpCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + UpCommand(context:DocumentContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class RmCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + RmCommand(context:DocumentContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
class ChangeDirCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + ChangeDirCommand(context:DocumentContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
ICommand <|-- AddTextCommand
AddTextCommand --> "_context" DocumentContext
AddTextCommand --> "_factory" TextFactory
ICommand <|-- PrintCommand
PrintCommand --> "_context" DocumentContext
ICommand <|-- PwdCommand
PwdCommand --> "_context" DocumentContext
ICommand <|-- UpCommand
UpCommand --> "_context" DocumentContext
ICommand <|-- RmCommand
RmCommand --> "_context" DocumentContext
ICommand <|-- ChangeDirCommand
ChangeDirCommand --> "_context" DocumentContext
class HelpCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + HelpCommand(registry:CommandRegistry)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
ICommand <|-- HelpCommand
HelpCommand --> "_registry" CommandRegistry
class ActCommand {
    + Keyword : string <<get>>
    + Description : string <<get>>
    + ActCommand(system:ICombatSystem, context:WorldContext)
    + Execute(args:string[], options:Dictionary<string, string>) : void
}
ICommand <|-- ActCommand
ActCommand --> "_system" ICombatSystem
ActCommand --> "_context" WorldContext
@enduml
