@startuml
class CompositeLogger {
    + Add(logger:ICombatLogger) : void
    + LogAttack(result:AttackResult) : void
    + LogAbility(result:AbilityResult) : void
    + LogHeal(result:HealResult) : void
    + LogMessage(message:string) : void
}
class "List`1"<T> {
}
ICombatLogger <|-- CompositeLogger
CompositeLogger o-> "_loggers<ICombatLogger>" "List`1"
@enduml
