@startuml
class ConsoleLogger {
    + LogAttack(result:AttackResult) : void
    + LogAbility(result:AbilityResult) : void
    + LogHeal(result:HealResult) : void
    + LogMessage(message:string) : void
}
ICombatLogger <|-- ConsoleLogger
ConsoleLogger o-> "_formatter" CombatFormatter
@enduml
