@startuml
interface ICombatEntity {
    Name : string <<get>>
    IsAlive : bool <<get>>
    TakeDamage(amount:int) : void
    Heal(amount:int) : void
    GetStats() : CharacterStats
    GetAbilities() : IEnumerable<Ability>
}
@enduml
