@startuml
abstract class Item {
    + Name : string <<get>>
    + AttackBonus : int <<get>> <<protected set>>
    + ArmorBonus : int <<get>> <<protected set>>
    + HealthBonus : int <<get>> <<protected set>>
    # Item(name:string, attack:int, armor:int, health:int, ability:Ability?)
}
Item --> "GrantedAbility" Ability
@enduml
