@startuml
abstract class Character {
    + Name : string <<get>>
    # Character(name:string)
    # SetBaseStat(type:StatType, value:int) : void
    + IsAlive : bool <<get>>
    - GetCurrentHealth() : int
    + TakeDamage(amount:int) : void
    + Heal(amount:int) : void
    + EquipItem(item:Item) : void
    + LearnAbility(ability:Ability) : void
    + GetStats() : CharacterStats
    + GetAbilities() : IEnumerable<Ability>
}
class "List`1"<T> {
}
ICombatEntity <|-- Character
Character --> "_baseStats" CharacterStats
Character o-> "_equipment<Item>" "List`1"
Character o-> "_abilities<Ability>" "List`1"
@enduml
