@startuml
abstract class Item {
    + Name : string <<get>>
    # Item(name:string)
    # AddModifier(type:StatType, amount:int) : void
}
class "Dictionary`2"<T1,T2> {
}
Item --> "GrantedAbility" Ability
Item o-> "Modifiers<StatType,int>" "Dictionary`2"
@enduml
